apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${CLUSTER_NAME}
  name: ${CLUSTER_NAME}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${CLUSTER_NAME}
  template:
    metadata:
      labels:
        app: ${CLUSTER_NAME}
    spec:
      containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          name: ${CLUSTER_NAME}-container
          ports:
            - containerPort: ${PORT}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${CLUSTER_NAME}
  name: ${CLUSTER_NAME}-service
spec:
  ports:
    - port: ${PORT}
      protocol: TCP
  selector:
    app: ${CLUSTER_NAME}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${CLUSTER_NAME}-ingress
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ${CLUSTER_NAME}-service
              servicePort: ${PORT}
